// Bob's Burgers episodes data (same as before)
const episodes = [
    // Season 1
    {season: 1, episode: 1, title: "Human Flesh", description: "Bob's burgers are suspected to be made of human flesh."},
    {season: 1, episode: 2, title: "Crawl Space", description: "Bob gets stuck in the walls of the restaurant."},
    {season: 1, episode: 3, title: "Sacred Couch", description: "The Belchers get a new couch but can't agree on the old one."},
    {season: 1, episode: 4, title: "Sexy Dance Fighting", description: "Tina joins a martial arts class to impress Jimmy Jr."},
    {season: 1, episode: 5, title: "Hamburger Dinner Theater", description: "Bob creates a dinner theater to compete with a fancy restaurant."},
    {season: 1, episode: 6, title: "Sheesh! Cab, Bob?", description: "Bob becomes a taxi driver to make extra money."},
    {season: 1, episode: 7, title: "Bed & Breakfast", description: "Linda turns the apartment into a bed and breakfast."},
    {season: 1, episode: 8, title: "Art Crawl", description: "Linda's art becomes controversial in the local art show."},
    {season: 1, episode: 9, title: "Spaghetti Western and Meatballs", description: "Bob enters a spaghetti western cooking contest."},
    {season: 1, episode: 10, title: "Burger War", description: "Bob and Jimmy Pesto get into a heated rivalry."},
    {season: 1, episode: 11, title: "Weekend at Mort's", description: "The kids spend the weekend at Mort's funeral home."},
    {season: 1, episode: 12, title: "Lobsterfest", description: "Bob competes in the annual Lobsterfest competition."},
    {season: 1, episode: 13, title: "Torpedo", description: "Bob's old friend visits with his wrestling persona."},

    // Season 2
    {season: 2, episode: 1, title: "The Belchies", description: "The kids explore an abandoned taffy factory."},
    {season: 2, episode: 2, title: "Bob Day Afternoon", description: "Bob gets caught in the middle of a bank robbery."},
    {season: 2, episode: 3, title: "Synchronized Swimming", description: "Tina joins the synchronized swimming team."},
    {season: 2, episode: 4, title: "Burgerboss", description: "Bob becomes obsessed with an arcade game."},
    {season: 2, episode: 5, title: "Food Truckin'", description: "The Belchers start a food truck business."},
    {season: 2, episode: 6, title: "Dr. Yap", description: "Bob gets dental work done by the eccentric Dr. Yap."},
    {season: 2, episode: 7, title: "Moody Foodie", description: "A food critic visits the restaurant."},
    {season: 2, episode: 8, title: "Bad Tina", description: "Tina tries to be rebellious and cool."},
    {season: 2, episode: 9, title: "Beefsquatch", description: "Gene appears on a cooking show and creates chaos."},

    // Season 3
    {season: 3, episode: 1, title: "Ear-sy Rider", description: "Louise's bunny ears are stolen by a biker gang."},
    {season: 3, episode: 2, title: "Full Bars", description: "The kids go trick-or-treating in a rich neighborhood."},
    {season: 3, episode: 3, title: "Bob Fires the Kids", description: "Bob fires the kids from working at the restaurant."},
    {season: 3, episode: 4, title: "Mutiny on the Windbreaker", description: "Bob takes a cooking class on a cruise ship."},
    {season: 3, episode: 5, title: "An Indecent Thanksgiving Proposal", description: "Bob cooks Thanksgiving dinner for Mr. Fischoeder's dinner party."},
    {season: 3, episode: 6, title: "The Deepening", description: "A mechanical shark terrorizes the town's harbor."},
    {season: 3, episode: 7, title: "Tina-rannosaurus Wrecks", description: "Tina crashes Bob's car in the parking lot."},
    {season: 3, episode: 8, title: "The Unbearable Like-Likeness of Gene", description: "Gene writes a song about his crush."},
    {season: 3, episode: 9, title: "God Rest Ye Merry Gentle-Mannequins", description: "Bob becomes obsessed with a department store mannequin."},
    {season: 3, episode: 10, title: "Mother Daughter Laser Razor", description: "Linda and Louise go to a mother-daughter seminar."},

    // Season 4
    {season: 4, episode: 1, title: "A River Runs Through Bob", description: "Bob goes on a camping trip with the Belcher family."},
    {season: 4, episode: 2, title: "Fort Night", description: "Tina and her friends have a sleepover in a pillow fort."},
    {season: 4, episode: 3, title: "Seaplane!", description: "The family goes on a seaplane trip that goes awry."},
    {season: 4, episode: 4, title: "My Big Fat Greek Bob", description: "Bob helps cater a Greek wedding."},
    {season: 4, episode: 5, title: "Turkey in a Can", description: "Someone keeps putting the Thanksgiving turkey in the toilet."},
    {season: 4, episode: 6, title: "Purple Rain-Union", description: "Linda attends her high school reunion."},
    {season: 4, episode: 7, title: "Bob and Deliver", description: "Bob becomes a substitute home economics teacher."},
    {season: 4, episode: 8, title: "Christmas in the Car", description: "The family gets stuck in a traffic jam on Christmas Eve."},
    {season: 4, episode: 9, title: "Slumber Party", description: "Louise reluctantly hosts a slumber party."},
    {season: 4, episode: 10, title: "Presto Tina-o", description: "Tina becomes a magician's assistant."},

    // Season 5
    {season: 5, episode: 1, title: "Work Hard or Die Trying, Girl", description: "The kids put on a school play about working hard."},
    {season: 5, episode: 2, title: "Tina and the Real Ghost", description: "Tina believes she's communicating with a ghost."},
    {season: 5, episode: 3, title: "Friends with Burger-fits", description: "Bob makes a new friend who might be using him."},
    {season: 5, episode: 4, title: "Dawn of the Peck", description: "The family splits up on Thanksgiving - some go to the wharf, others to the turkey trot."},
    {season: 5, episode: 5, title: "Best Burger", description: "Bob enters a burger competition against other local restaurants."},
    {season: 5, episode: 6, title: "Father of the Bob", description: "Bob's father visits for Christmas."},
    {season: 5, episode: 7, title: "Tina Tailor Soldier Spy", description: "Tina goes undercover to find out who's been starting food fights."},
    {season: 5, episode: 8, title: "Midday Run", description: "Tina has to return a movie on time to avoid late fees."},
    {season: 5, episode: 9, title: "Speakeasy Rider", description: "Bob and Linda go to a secret underground speakeasy."},
    {season: 5, episode: 10, title: "Late Afternoon in the Garden of Bob and Louise", description: "Bob and Louise are locked in the school garden."},

    // Season 6
    {season: 6, episode: 1, title: "Sliding Bobs", description: "Bob imagines what life would be like if he never met Linda."},
    {season: 6, episode: 2, title: "The Land Ship", description: "The kids discover a ship playground that's about to be destroyed."},
    {season: 6, episode: 3, title: "The Hauntening", description: "Louise's friends throw her a surprise haunted house party."},
    {season: 6, episode: 4, title: "Gayle Makin' Bob Sled", description: "Bob reluctantly helps Gayle with her problems."},
    {season: 6, episode: 5, title: "Nice-Capades", description: "The kids put on an ice show to help save the ice rink."},
    {season: 6, episode: 6, title: "The Cook, the Steve, the Gayle, & Her Lover", description: "Gayle brings her new boyfriend to Thanksgiving dinner."},
    {season: 6, episode: 7, title: "The Gene and Courtney Show", description: "Gene and Courtney start a morning radio show."},
    {season: 6, episode: 8, title: "Sexy Dance Healing", description: "Bob hurts his back and Linda tries alternative healing methods."},
    {season: 6, episode: 9, title: "Sacred Couch", description: "The Belchers shop for a new couch and get caught up in the store's drama."},
    {season: 6, episode: 10, title: "Lice Things Are Lice", description: "The school has a lice outbreak and parents go crazy."},

    // Season 7
    {season: 7, episode: 1, title: "Flu-ouise", description: "Louise has a fever dream while sick with the flu."},
    {season: 7, episode: 2, title: "Sea Me Now", description: "The kids go on a field trip to the aquarium."},
    {season: 7, episode: 3, title: "Teen-a Witch", description: "Tina becomes convinced she's a witch."},
    {season: 7, episode: 4, title: "They Serve Horses, Don't They?", description: "The kids think a local restaurant serves horse meat."},
    {season: 7, episode: 5, title: "Large Brother, Where Fart Thou?", description: "Gene gets a Big Brother through a mentorship program."},
    {season: 7, episode: 6, title: "The Quirk-ducers", description: "The kids produce their own version of the Thanksgiving play."},
    {season: 7, episode: 7, title: "The Last Gingerbread House on the Left", description: "The family enters a gingerbread house competition."},
    {season: 7, episode: 8, title: "Ex MachTina", description: "Tina becomes obsessed with a futuristic smart toilet."},
    {season: 7, episode: 9, title: "Bob Actually", description: "Multiple Valentine's Day stories unfold in this anthology episode."},
    {season: 7, episode: 10, title: "There's No Business Like Mr. Business Business", description: "Linda's sister Gayle loses her cat Mr. Business."},

    // Season 8
    {season: 8, episode: 1, title: "Brunchsquatch", description: "Bob creates a new brunch menu to compete with other restaurants."},
    {season: 8, episode: 2, title: "The Silence of the Louise", description: "Louise goes to speech therapy to work on her lisp."},
    {season: 8, episode: 3, title: "The Wolf of Wharf Street", description: "The kids start their own business selling tickets to a fake event."},
    {season: 8, episode: 4, title: "Sit Me Baby One More Time", description: "The kids offer babysitting services to make money."},
    {season: 8, episode: 5, title: "Thanks-hoarding", description: "The family tries to help their hoarder neighbor with Thanksgiving."},
    {season: 8, episode: 6, title: "The Bleakening", description: "A two-part Christmas special where the kids search for the missing Christmas tree topper."},
    {season: 8, episode: 7, title: "The Bleakening", description: "Part two of the Christmas special."},
    {season: 8, episode: 8, title: "V for Valentine-detta", description: "Linda and Gayle get into a fight over Valentine's Day plans."},
    {season: 8, episode: 9, title: "The Secret Ceramics Room of Secrets", description: "The kids discover a secret ceramics room in the school."},
    {season: 8, episode: 10, title: "The Geography of Global Flavor", description: "Bob helps Gene with a geography project about global cuisine."},

    // Season 9
    {season: 9, episode: 1, title: "Just One of the Boyz 4 Now for Now", description: "Tina goes to a Boyz 4 Now concert and meets her idol."},
    {season: 9, episode: 2, title: "The Taking of Funtime One Two Three", description: "The kids get trapped in a Funtime Funhouse."},
    {season: 9, episode: 3, title: "Tweentrepreneurs", description: "The kids start a business to fund their summer plans."},
    {season: 9, episode: 4, title: "Nightmare on Ocean Avenue Street", description: "The kids' Halloween plans are ruined by a storm."},
    {season: 9, episode: 5, title: "Live and Let Fly", description: "Gene is afraid to perform his music in front of people."},
    {season: 9, episode: 6, title: "Bobby Driver", description: "Bob becomes a driver for a wealthy family."},
    {season: 9, episode: 7, title: "I Bob Your Pardon", description: "Bob accidentally orders 25 Thanksgiving turkeys."},
    {season: 9, episode: 8, title: "Roller? I Hardly Know Her!", description: "Gene starts a romance with the roller rink DJ."},
    {season: 9, episode: 9, title: "UFO No You Didn't", description: "The kids investigate strange lights in the sky."},
    {season: 9, episode: 10, title: "Better Off Sled", description: "The kids go sledding and compete in an underground sled race."},

    // Season 10
    {season: 10, episode: 1, title: "The Ring (But Not Scary)", description: "Bob and Linda try to recreate their wedding."},
    {season: 10, episode: 2, title: "Boys Just Wanna Have Fungus", description: "Bob and Gene bond over mushroom foraging."},
    {season: 10, episode: 3, title: "Motor, She Boat", description: "Tina tries to save a old boat from being scrapped."},
    {season: 10, episode: 4, title: "Pig Trouble in Little Tina", description: "Tina has to take care of a pig for her school project."},
    {season: 10, episode: 5, title: "Legends of the Mall", description: "The kids explore the abandoned parts of the mall."},
    {season: 10, episode: 6, title: "The Hawkings: Look Who's Hawking Now!", description: "Bob becomes obsessed with bird watching."},
    {season: 10, episode: 7, title: "Land of the Loft", description: "Linda creates a loft bedroom but it becomes a disaster."},
    {season: 10, episode: 8, title: "Now We're Not Cooking with Gas", description: "The restaurant's gas gets shut off on a busy day."},
    {season: 10, episode: 9, title: "All That Gene", description: "Gene auditions for a talented kid competition show."},
    {season: 10, episode: 10, title: "Have Yourself a Maily Linda Christmas", description: "Linda becomes the neighborhood's unofficial mail carrier."},

    // Season 11
    {season: 11, episode: 1, title: "Dream a Little Bob of Bob", description: "Bob has strange dreams about a mysterious figure."},
    {season: 11, episode: 2, title: "Worms of In-Rear-Ment", description: "The kids get in trouble and are sentenced to community service."},
    {season: 11, episode: 3, title: "Copa-Bob-ana", description: "Bob tries to learn to dance for Linda's birthday."},
    {season: 11, episode: 4, title: "Heartbreak Hotel-oween", description: "Louise's Halloween plans are ruined when she gets sick."},
    {season: 11, episode: 5, title: "Fast Time Capsules at Wagstaff School", description: "The kids help create a time capsule for their school."},
    {season: 11, episode: 6, title: "Bob Belcher and the Terrible, Horrible, No Good, Very Bad Kids", description: "Bob has a particularly challenging day with the kids."},
    {season: 11, episode: 7, title: "Diarrhea of a Poopy Kid", description: "Gene writes a report about diarrhea that becomes popular."},
    {season: 11, episode: 8, title: "The Terminalator II: Terminals of Endearment", description: "The family gets stuck at the airport during a layover."},
    {season: 11, episode: 9, title: "Mommy Boy", description: "Gene becomes a mama's boy and Linda loves the attention."},
    {season: 11, episode: 10, title: "Yachty or Nice", description: "The family gets invited to a fancy yacht party."},

    // Season 12
    {season: 12, episode: 1, title: "Manic Pixie Crap Show", description: "Louise becomes obsessed with a charismatic new student."},
    {season: 12, episode: 2, title: "Crystal Mess", description: "Linda becomes obsessed with crystals and their supposed healing powers."},
    {season: 12, episode: 3, title: "The Pumpkinening", description: "The kids investigate mysterious pumpkin thefts in the neighborhood."},
    {season: 12, episode: 4, title: "Driving Big Dummy", description: "Bob teaches Tina how to drive."},
    {season: 12, episode: 5, title: "Seven-tween Again", description: "Gene acts younger to get attention."},
    {season: 12, episode: 6, title: "Beach, Please", description: "The family goes to the beach but everything goes wrong."},
    {season: 12, episode: 7, title: "Loft in Bedslation", description: "Linda tries to create a romantic loft bedroom."},
    {season: 12, episode: 8, title: "Stuck in the Kitchen with You", description: "Bob and Linda are trapped in the kitchen during a power outage."},
    {season: 12, episode: 9, title: "FOMO You Didn't", description: "Tina experiences FOMO when she can't attend a party."},
    {season: 12, episode: 10, title: "Gene's Christmas Break", description: "Gene tries to make Christmas special for everyone."},

    // Season 13
    {season: 13, episode: 1, title: "To Bob, or Not to Bob", description: "Bob questions whether he should continue running the restaurant."},
    {season: 13, episode: 2, title: "The Reeky Lake Show", description: "The kids create their own talk show."},
    {season: 13, episode: 3, title: "What About Sleepover?", description: "Louise has her first sleepover and it doesn't go as planned."},
    {season: 13, episode: 4, title: "Comet-y of Errors", description: "The family tries to view a rare comet but everything goes wrong."},
    {season: 13, episode: 5, title: "So You Stink You Can Dance", description: "The kids enter a dance competition."},
    {season: 13, episode: 6, title: "Apple Gore-chard! (But Not Gory)", description: "The family visits an apple orchard for a fun day out."},
    {season: 13, episode: 7, title: "Ready Player Gene", description: "Gene becomes obsessed with a new video game."},
    {season: 13, episode: 8, title: "Putts-giving", description: "The family goes mini-golfing on Thanksgiving."},
    {season: 13, episode: 9, title: "Show Mama From the Grave", description: "Linda tries to honor her deceased mother."},
    {season: 13, episode: 10, title: "The Plight Before Christmas", description: "The family's Christmas plans are disrupted by a snowstorm."},

    // Season 14
    {season: 14, episode: 1, title: "Fight at the Not-Okay Chore-ral", description: "The kids rebel against doing chores."},
    {season: 14, episode: 2, title: "The Amazing Rudy", description: "Rudy becomes a magician and the kids help with his act."},
    {season: 14, episode: 3, title: "The Pickleorette", description: "Linda plans Gayle's bachelorette party."},
    {season: 14, episode: 4, title: "Running Down a Gene", description: "Gene trains for a marathon to impress a girl."},
    {season: 14, episode: 5, title: "Bully-ieve It or Not", description: "Louise deals with a bully at school."},
    {season: 14, episode: 6, title: "Escape from Which Island", description: "The family gets stranded on a small island."},
    {season: 14, episode: 7, title: "Dine and Bash", description: "Bob caters a fancy dinner party."},
    {season: 14, episode: 8, title: "Wharf, Me Worry?", description: "The kids explore the wharf and get into trouble."},
    {season: 14, episode: 9, title: "The Big Stieblitzki", description: "Gene enters a music competition."},
    {season: 14, episode: 10, title: "The Nightmare 2 Days Before Christmas", description: "Christmas preparations go hilariously wrong."}
];
